# Generated by Django 5.0.6 on 2024-06-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_planning_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='planning.state'),
        ),
    ]
