# Generated by Django 5.0.6 on 2024-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_planning_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='tracebility',
            field=models.IntegerField(null=True),
        ),
    ]
