# Generated by Django 5.0.6 on 2025-05-03 14:32

import django.db.models.deletion
from django.db import migrations, models
from event.utils import populate_options

class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('endTime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
        migrations.AddField(
            model_name='event',
            name='stateEvent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='event.stateevent'),
        ),
        migrations.RunPython(populate_options, reverse_code=migrations.RunPython.noop),
    ]
