# Generated by Django 5.0.6 on 2025-05-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_stateevent_delete_dummy_event_stateevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stateEvent',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='event.stateevent'),
        ),
    ]
